### ISSUE TITLE
Improve documentation with examples

### ISSUE THREAD

**Issue by Arghnews** [igormironchik/args-parser#10]
This library looks well featured and nicely designed.

Please add at least one more example to the README page that shows *simple* usage. Not subcommands. Just a simple example with parsing for a boolean flag, and an option with an argument. I'm an idiot, but nevertheless it still took me far me too long to find how to do this. For something as simple as an argparser, people want to copy and paste an example and edit it so they can get up and running quickly - putting only one example program (of the new version) on the README page that is subcommands is confusing.

Even better would be an example program showcasing several types of options, flags, options with argument(s), groups (if supported) etc.

All the best. In case it matters, I'm now using this library via conan after trying to use argh and being unable to understand it too.

**Comment by igormironchik** [comment]
Done.

[Here](http://igormironchik.github.io/args-parser/) you can find Doxygen-generated documentation. But not all methods of `CmdLine` is in right place, because of issue in Doxygen. Additional methods of `CmdLine` is documented [here](http://igormironchik.github.io/args-parser/class_args_1_1details_1_1_a_p_i_3_01_p_a_r_e_n_t_00_01_s_e_l_f_00_01_a_r_g_p_t_r_00_01true_01_4.html).
